### ISSUE TITLE
Deploy via API fails

### ISSUE THREAD

**Issue by webfolkcreative** [jbrooksuk/laravel-forge-action#20]
Hey there!

I'm unable to get your `Deploy via API` example working. I'm not sure if something has changed in Forge, but the `Deployment Trigger URL` example works perfectly fine. Any ideas on why it might be failing? All secrets have been created for testing, and it looks like the job is grabbing them properly. Error thrown is:

```
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Comment by jbrooksuk** [comment]
Thanks! Can you try using v1.0.3? https://github.com/jbrooksuk/laravel-forge-action/releases/tag/v1.0.3

**Comment by webfolkcreative** [comment]
@jbrooksuk Just tried with 1.0.3 and unfortunately I am still receiving the same error as before.

**Comment by webfolkcreative** [comment]
After some reading, I think it's related to CURL using HTTP/2, some people have fixed other error messages by adding `--http1.1` to the CURL command.
